module.exports = [
  "https://raw.githubusercontent.com/oss-review-toolkit/ort/main/logos/logo.png",
  "https://raw.githubusercontent.com/porscheofficial/cookie-consent-banner/main/assets/logo.svg",
  "https://raw.githubusercontent.com/porscheofficial/porschedigital-technology-radar/refs/heads/pdig/public/logo.svg",
  "https://raw.githubusercontent.com/porsche-design-system/porsche-design-system/main/packages/assets/projects/crest/src/porsche-crest%403x.png",
  "https://gitlab.com/uploads/-/system/group/avatar/13943452/terraform-icon.png?width=500.png",
  "https://eslint.org/icon-512.png",
  "https://developer.android.com/static/images/brand/android-head_flat.png",
  "https://raw.githubusercontent.com/mbeddr/mbeddr.core/master/logos/2013/blue_orange/LogoBigTransparent.png",
  "https://uploads-ssl.webflow.com/6419a4c2c9609e21b02a47e8/6454e539d4ea54c08e42aedb_Frame%2010683.png",
  "https://newsroom.porsche.com/.imaging/mte/porsche-templating-theme/image_690x388/dam/pnr/other/executive-board/Meschke/pictures-NEW/New/Meschke1.jpg/jcr:content/Meschke1.jpg",
  "https://www.linuxfoundation.org/hubfs/OSPO_FeaturedImage.png",
  "https://github-production-user-asset-6210df.s3.amazonaws.com/43671777/287491838-0a4cfd31-89fb-49d6-a38b-797f4c20c40f.png",
  "https://raw.githubusercontent.com/todogroup/ospology/main/ospo-book/static/images/ospo-book-social.jpg",
];
