name: OSO Repolinter

on: [push, workflow_dispatch]

jobs:
  # =============================================================================
  # JOB: REPOLINTER
  # =============================================================================
  analyzer:
    runs-on: ubuntu-latest
    name: OSO Repolinter
    steps:
      - uses: actions/checkout@v3
      - name: Run OSO Repolinter
        id: repolinter
        uses: porscheofficial/.github/workflows/repolinter@main
        with:
          is-distributed: true
